/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'zafu' at '12/5/16 7:14 PM' with Gradle 2.3
 *
 * @author zafu, @date 12/5/16 7:14 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
